# Generated by Django 2.2.4 on 2020-12-25 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whcapp', '0003_auto_20201225_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.TextField(),
        ),
    ]
