# Generated by Django 2.2.4 on 2020-12-26 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('whcapp', '0003_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user_comment',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='post_comment',
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='m_comments', to='whcapp.Post'),
            preserve_default=False,
        ),
    ]
