# Generated by Django 2.2.4 on 2020-12-26 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whcapp', '0004_auto_20201225_2014'),
        ('whcapp', '0004_auto_20201226_1117'),
    ]

    operations = [
    ]
