# Generated by Django 2.2.4 on 2020-12-26 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whcapp', '0005_merge_20201226_1419'),
        ('whcapp', '0005_merge_20201226_1512'),
    ]

    operations = [
    ]
